// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAivdn6MV25032F7UL7dCr9Jao-vFL-jcQ',
    appId: '1:419182351833:web:f99609954acc7182af35c8',
    messagingSenderId: '419182351833',
    projectId: 'pushnotificationproject-b5145',
    authDomain: 'pushnotificationproject-b5145.firebaseapp.com',
    storageBucket: 'pushnotificationproject-b5145.firebasestorage.app',
    measurementId: 'G-LC13N7TYR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BXlHer0nG3lfFfLefpZ8FuUDXsCC6Fs',
    appId: '1:419182351833:android:a35501463f84d0baaf35c8',
    messagingSenderId: '419182351833',
    projectId: 'pushnotificationproject-b5145',
    storageBucket: 'pushnotificationproject-b5145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrh-2K0aiOxVNP8Iy44EBYFc5BfqkOoUg',
    appId: '1:419182351833:ios:617c51a8a5a03bb0af35c8',
    messagingSenderId: '419182351833',
    projectId: 'pushnotificationproject-b5145',
    storageBucket: 'pushnotificationproject-b5145.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrh-2K0aiOxVNP8Iy44EBYFc5BfqkOoUg',
    appId: '1:419182351833:ios:617c51a8a5a03bb0af35c8',
    messagingSenderId: '419182351833',
    projectId: 'pushnotificationproject-b5145',
    storageBucket: 'pushnotificationproject-b5145.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAivdn6MV25032F7UL7dCr9Jao-vFL-jcQ',
    appId: '1:419182351833:web:f92c47d3373948bbaf35c8',
    messagingSenderId: '419182351833',
    projectId: 'pushnotificationproject-b5145',
    authDomain: 'pushnotificationproject-b5145.firebaseapp.com',
    storageBucket: 'pushnotificationproject-b5145.firebasestorage.app',
    measurementId: 'G-HJBQVHTQDX',
  );

}